name: Build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  buildAndDeploy2Dev:
    name: "Build and Deploy"
    runs-on: self-hosted
    env:
      WERF_KUBE_CONTEXT: "main-aws"
      ENV: "redis-operator"

    steps:
      - name: werf converge
        uses: werf/actions/converge@v1.1
        with:
          channel: alpha
          env: ${{ env.ENV }}
        env:
          WERF_STAGES_STORAGE: "ghcr.io/cmtt-ru/stages-${{ github.event.repository.name }}"
          WERF_IMAGES_REPO: "ghcr.io/cmtt-ru/${{ github.event.repository.name }}"
